# -*- coding: utf-8 -*-
"""Problema 5 - Domino Piling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRUYoSG6eFklWmBmy5bxfB46kdx7X0BJ
"""

dimensionesTablero = input()
numeroDeDominos = 0

listaDeDigitos = [int(s) for s in dimensionesTablero.split() if s.isdigit()]

m = int(listaDeDigitos[0])
n = int(listaDeDigitos[1])

numeroDeDominos = (m * n) // 2

print(numeroDeDominos)